/*
 * Copyright (c) 2026. The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.googlesource.gerrit.plugins.reviewai.aibackend.common.client.api.gerrit;

import com.google.inject.Singleton;
import com.googlesource.gerrit.plugins.reviewai.aibackend.common.client.messages.ClientMessageCleaner;
import com.googlesource.gerrit.plugins.reviewai.aibackend.common.model.api.gerrit.GerritComment;
import com.googlesource.gerrit.plugins.reviewai.config.Configuration;
import com.googlesource.gerrit.plugins.reviewai.localization.Localizer;
import com.googlesource.gerrit.plugins.reviewai.settings.Settings;
import com.googlesource.gerrit.plugins.reviewai.web.model.AiReviewHistoryInfo;
import lombok.extern.slf4j.Slf4j;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.regex.Pattern;
import java.util.stream.Stream;

@Singleton
@Slf4j
public class GerritAiReviewHistoryCollector {
  public AiReviewHistoryInfo collect(
      Configuration config,
      Localizer localizer,
      int aiAccountId,
      Map<String, List<GerritComment>> inlineComments) {
    Pattern botMentionPattern = getBotMentionPattern(config);
    List<GerritComment> comments = flattenComments(inlineComments);
    Map<String, GerritComment> commentsById = new HashMap<>();
    for (GerritComment comment : comments) {
      if (comment.getId() != null) {
        commentsById.put(comment.getId(), comment);
      }
    }

    HashSet<String> threadRootIds = new HashSet<>();
    for (GerritComment comment : comments) {
      if (isDirectedToAi(comment, aiAccountId, botMentionPattern)) {
        threadRootIds.add(comment.getId());
      }
    }

    List<AiReviewHistoryInfo.Entry> entries = new ArrayList<>();
    for (GerritComment comment : comments) {
      if (!belongsToConversation(comment, threadRootIds, commentsById)) {
        continue;
      }
      addConversationEntry(entries, config, localizer, aiAccountId, comment);
    }

    entries.sort(
        Comparator.comparing(AiReviewHistoryInfo.Entry::getUpdated, Comparator.nullsLast(String::compareTo))
            .thenComparing(AiReviewHistoryInfo.Entry::getId, Comparator.nullsLast(String::compareTo)));

    return new AiReviewHistoryInfo(entries);
  }

  private List<GerritComment> flattenComments(Map<String, List<GerritComment>> inlineComments) {
    List<GerritComment> comments = new ArrayList<>();
    for (Map.Entry<String, List<GerritComment>> entry : inlineComments.entrySet()) {
      for (GerritComment comment : entry.getValue()) {
        if (comment.getFilename() == null) {
          comment.setFilename(entry.getKey());
        }
        comments.add(comment);
      }
    }
    comments.sort(
        Comparator.comparing(this::getUpdated, Comparator.nullsLast(String::compareTo))
            .thenComparing(GerritComment::getId, Comparator.nullsLast(String::compareTo)));
    return comments;
  }

  private void addConversationEntry(
      List<AiReviewHistoryInfo.Entry> entries,
      Configuration config,
      Localizer localizer,
      int aiAccountId,
      GerritComment comment) {
    boolean fromAi = isFromAi(comment, aiAccountId);

    ClientMessageCleaner cleaner =
        new ClientMessageCleaner(config, Optional.ofNullable(comment.getMessage()).orElse(""), localizer);
    if (fromAi) {
      cleaner.removeDebugCodeBlocks();
    } else {
      cleaner.removeMentions().removeCommands();
    }
    String cleanedMessage = cleaner.removeHeadings().getMessage().trim();
    if (cleanedMessage.isEmpty()) {
      return;
    }

    entries.add(
        new AiReviewHistoryInfo.Entry(
            comment.getId(),
            fromAi ? Settings.OPENAI_ROLE_ASSISTANT : Settings.OPENAI_ROLE_USER,
            getAuthorName(comment),
            getUpdated(comment),
            comment.getPatchSet(),
            toDisplayFilename(comment.getFilename()),
            comment.getLine(),
            cleanedMessage));
  }

  private boolean isDirectedToAi(GerritComment comment, int aiAccountId, Pattern botMentionPattern) {
    if (comment == null || comment.getAuthor() == null || comment.isAutogenerated()) {
      return false;
    }
    if (comment.getAuthor().getAccountId() == aiAccountId) {
      return false;
    }
    String message = Optional.ofNullable(comment.getMessage()).orElse("");
    return !message.isBlank() && botMentionPattern.matcher(message).find();
  }

  private boolean belongsToConversation(
      GerritComment comment, HashSet<String> threadRootIds, Map<String, GerritComment> commentsById) {
    if (comment == null || comment.isAutogenerated()) {
      return false;
    }
    String currentId = comment.getId();
    if (currentId != null && threadRootIds.contains(currentId)) {
      return true;
    }
    String inReplyTo = comment.getInReplyTo();
    while (inReplyTo != null) {
      if (threadRootIds.contains(inReplyTo)) {
        return true;
      }
      GerritComment parent = commentsById.get(inReplyTo);
      inReplyTo = parent == null ? null : parent.getInReplyTo();
    }
    return false;
  }

  private boolean isFromAi(GerritComment comment, int aiAccountId) {
    return comment.getAuthor() != null && comment.getAuthor().getAccountId() == aiAccountId;
  }

  private Pattern getBotMentionPattern(Configuration config) {
    String escapedUserName = Pattern.quote(config.getGerritUserName());
    String userEmail = config.getGerritUserEmail();
    String userNameOrEmail =
        userEmail.isBlank() ? escapedUserName : escapedUserName + "|" + Pattern.quote(userEmail);
    return Pattern.compile("^(?!>).*?(?:@" + userNameOrEmail + ")\\b", Pattern.MULTILINE);
  }

  private String getAuthorName(GerritComment comment) {
    GerritComment.Author author = comment.getAuthor();
    return Stream.of(author.getDisplayName(), author.getName(), author.getUsername(), author.getEmail())
        .filter(value -> value != null && !value.isBlank())
        .findFirst()
        .orElse("Unknown");
  }

  private String getUpdated(GerritComment comment) {
    return Optional.ofNullable(comment.getUpdated()).orElse(comment.getDate());
  }

  private String toDisplayFilename(String filename) {
    if (Settings.GERRIT_PATCH_SET_FILENAME.equals(filename)) {
      return null;
    }
    return filename;
  }
}
